# Site Build Settings

# Jekyll-paginate-v2 configuration
#  pagination:
#   enabled: false
#   per_page: 4
#   permalink: '/page/:num/'
#   title: ':title - page :num of :max'
#   limit: 0
#   sort_field: 'date'
#   sort_reverse: true

# jekyll-paginate configuration
paginate:            4

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings 
title:		           'Haoyu Yue'
description:	       'A City Learner & Lover'
author:              'Haoyu'

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
