# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: ''

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Cities', path: 'menu', url: 'cities.html'}
- {name: 'Informatics', path: 'menu', url: 'informatics.html'}
- {name: 'More', path: 'menu', url: 'more.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://github.com/Yohaoyu'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/yohaoyu/'}
- {icon: 'envelope', link: 'mailto:yohaoyu@outlook.com'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Next'
  previous_page: 'Before'

related_posts: 'More:'

post_date_prefix: 'Written on'
